- name: install and start nginx
  hosts: frontend
  tasks:
  - name: nginx install
    ansible.builtin.package:
      name: nginx
      state: present

  - name: nginx start
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes