- name: functions
  hosts: local
  connection: local
  vars:
    name: "Arjun Reddy Keellapati"
    gmail: ARJUNreddy90@GMAIL.COM
    fruits: mangoes, apples, banananas, pomogranates
    ipaddress: "192.84.0.2"
    tags:
    # dictionary to list
      Application: payment
      Environment: dev
      # list to dictionary
    listtags:
      - key: Application
        value: payment
      - key: Environment
        value: dev
  tasks:
  - name: default function
    ansible.builtin.debug:
      msg: " hello {{ name | default('Ramesh') }}"

  - name: convert strings to list
    ansible.builtin.debug:
      msg: " fruits are {{ fruits | split(',') }}"

  - name: convert dictioary to list
    ansible.builtin.debug:
      msg: "tags are {{ tags | dict2items }}"

  - name: convert list to dictoionary
    ansible.builtin.debug:
      msg: "tags are {{ listtags | items2dict  }}"
  
  - name: read yaml and take into variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'student.yml') | from_yaml }}"

  - name: convert yaml to json
    ansible.builtin.debug:
      msg: "{{ student_yaml | to_yaml }}"

  - name: Copy JSON content to a file
    ansible.builtin.copy:
      dest: "./student-data.json"
      content: "{{ student_yaml | to_nice_json }}"

  - name: convert uppercase
    ansible.builtin.debug:
      msg: "name is {{ name | upper }}"

  - name: convert lowercase
    ansible.builtin.debug:
      msg: "name is {{ gmail | lower }}"

  - name: checking ipaddress valid or not 
    ansible.builtin.debug:
      msg: "name is {{ ipaddress | ansible.utils.ipv4 }}"

  - name: grep for root
    ansible.builtin.command: cat /etc/passwd | grep root
    register: command_output

  - name: print the output for command
    ansible.builtin.debug: 
      msg: "{{ command_output }}"


    