- name: functions
  hosts: local
  connection: local
  vars:
    fruits: mangoes, apples, banananas, pomogranates
    tags:
    Application: payment
    Environment: dev
  tasks:
  - name: default function
    ansible.builtin.debug:
      msg: " hello {{ name | default('Ramesh') }}"

  - name: convert strings to list
    ansible.builtin.debug:
      msg: " technogies are {{ fruits | split(',') }}"

  - name: convert dictioary to list
    ansible.builtin.debug:
      msg: "tags are {{ tags | | dict2items }}"