- name: user creation
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check user exist or not
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: true

  - name: print the output of user
    ansible.builtin.debug:
      msg: "{{ user_output }}"

  - name: create user
    ansible.builtin.command: id roboshop
    when: user_output.rc != 0
    
  