- name: Play-01
  hosts: frontend
  tasks:
  - name: play-01 and task-01
    debug:
      msg:"hello from play-01 and task-01"
  
  - name: play-01 and task-02
    debug:
      msg:"hello from play-01 and task-02"

- name: Play-02
  hosts: frontend
  tasks:
  - name: play-02 and task-01
    debug:
      msg:"hello from play-02 and task-01"
  
  - name: play-02 and task-02
    debug:
      msg:"hello from play-02 and task-02"



  
