- name: variables from file
  hosts: local
  connection: local
  vars_files:
  - course.yml
  tasks:
  - name: printing the student info
    ansible.builtin.debug:
      msg: "student name is: {{ NAME }}, class: {{ CLASS }}, branch: {{ BRANCH }}, collegename: {{ COLLEGENAME }}"
